// Dictionary Data
const dict = {
    id: {
        top_promo: "🔥 Buka Setiap Hari 08:00 - 20:00 WIB | Melayani Pesanan Dine-in, Takeaway & Online",
        nav_order: "Pesan", hero_btn_order: "Pesan Sekarang", hero_btn_menu: "Lihat Menu",
        gallery_text: "@sate.faqih1",

        nav_about: "Tentang", nav_menu: "Menu", nav_history: "Sejarah", nav_guests: "Galeri Foto", nav_reviews: "Review", nav_faq: "FAQ", nav_location: "Lokasi",
        
        hero_badge_0: "Warisan Lintas Generasi", hero_title_0_main: "Warung Sate", hero_title_0_sub: "H. Faqih 1", hero_sub_0: "Legendaris sejak 1950. Lebih dari sekadar kelezatan sate, ini adalah saksi bisu kebersamaan, nostalgia, dan cerita keluarga Anda.",
        hero_sub_0_mobile: "Legendaris sejak 1950. Saksi cita rasa, kebersamaan, dan nostalgia lintas generasi.",
        hero_sub_0_tablet: "Legendaris sejak 1950. Tempat sederhana dengan cita rasa, kebersamaan, dan nostalgia lintas generasi.",
        hero_badge_1: "Cita Rasa Autentik", hero_title_1_main: "Sate Kambing", hero_title_1_sub: "Legendaris", hero_sub_1: "Sate kambing  yang dibakar hingga matang sempurna, disajikan dengan siraman bumbu kacang/kecap yang gurih, taburan bawang merah segar, dan sambal pedas sebagai pelengkap. Perpaduan daging empuk, aroma bakaran arang, dan bumbu khas menghadirkan cita rasa sate yang autentik.",
        hero_sub_1_mobile: "Sate kambing empuk dengan bumbu gurih, aroma arang, bawang merah, dan sambal pedas.",
        hero_sub_1_tablet: "Sate kambing empuk dengan bumbu gurih, aroma bakaran arang, bawang merah segar, dan sambal pedas.",
        hero_badge_2: "Kuah Medok Kaya Rempah", hero_title_2_main: "Gule Kambing", hero_title_2_sub: "Spesial", hero_sub_2: "Dimasak perlahan berjam-jam menghasilkan daging super empuk dengan kuah rempah Nusantara yang kental dan menghangatkan.",
        hero_sub_2_mobile: "Gule kambing empuk dengan kuah rempah Nusantara yang hangat dan kaya rasa.",
        hero_sub_2_tablet: "Dimasak perlahan hingga empuk, dengan kuah rempah Nusantara yang hangat, kental, dan kaya rasa.",
        
        nostalgia_title: "Ruang Memori Lintas Generasi",
        nostalgia_desc: "Warung Sate H. Faqih 1 bukanlah sekadar tempat singgah untuk bersantap. Di sini, meja dan kursi kami menjadi saksi bisu dari kakek yang mengenalkan rasa otentik kepada cucunya, hingga para <span class='font-bold text-brand-orange'>santri, warga sekitar, keluarga, dan pendatang</span> yang selalu kembali karena rindu pada cita rasa khas Cukir. Setiap kepulan asap sate membawa kehangatan cerita, kebersamaan, dan silaturahmi yang tak pernah putus sejak 1950.",
        
        fac_title: "Kenyamanan Anda Prioritas Kami", fac_1: "Suasana Nyaman", fac_2: "Ramah Keluarga", fac_3: "Cocok untuk Rombongan", fac_4: "Pelayanan Ramah",

        menu_subtitle: "Warisan Rasa", menu_title: "Menu Unggulan Kami", menu_instruction: "Klik foto untuk melihat detail menu.",
        menu_badge_best: "Terlaris", menu_badge_family: "Favorit Keluarga", menu_badge_recommended: "Rekomendasi", menu_badge_texture: "Favorit Pecinta Tekstur", menu_detail_link: "Klik untuk Detail",
        menu_type_sate: "Aneka Sate", menu_type_gule: "Aneka Gule & Berkuah",
        menu_1_title: "Sate Kambing", menu_1_short: "Potongan daging kambing pilihan yang sangat empuk, dibakar sempurna di atas arang.", menu_1_char: "Tanpa prengus, disajikan dengan kecap & irisan bawang segar.", menu_1_desc: "Inilah menu andalan kami yang tak lekang oleh waktu. Menggunakan daging kambing  pilihan yang dipotong dengan ukuran pas, kemudian dibakar menggunakan arang kayu untuk menghasilkan tingkat kematangan sempurna. Dagingnya empuk, juicy, dan sama sekali tidak prengus.", menu_1_extra: "Sangat direkomendasikan dinikmati bersama nasi hangat dan teh manis panas.",
        menu_2_title: "Sate Ayam Legendaris", menu_2_short: "Daging ayam tebal dan juicy, dilumuri bumbu kacang rahasia yang legit dan meresap hingga ke dalam serat daging.", menu_2_char: "Bumbu kacang ditumbuk manual, tekstur autentik.", menu_2_desc: "Favorit lintas generasi. Daging ayam segar yang dibakar hingga kecoklatan, disiram dengan bumbu kacang resep warisan H. Faqih yang diolah secara manual untuk mempertahankan tekstur legit dan rasa manis gurih yang khas.", menu_2_extra: "Menu favorit anak-anak dan cocok untuk porsi makan keluarga besar.",
        menu_3_title: "Gule Kambing Spesial", menu_3_short: "Kuah gule bersantan kental kaya rempah Nusantara, dimasak perlahan bersama potongan daging dan tulang.", menu_3_char: "Kuah medok, daging sangat mudah lepas dari tulang.", menu_3_desc: "Pendamping wajib makan sate. Kuah gule kami dimasak selama berjam-jam menggunakan rempah-rempah tradisional pilihan, menghasilkan kuah yang kental, medok, dan sangat kaya rasa. Isian daging dan jeroan di dalamnya sangat lembut.", menu_3_extra: "Dapat dipesan dengan isian campur atau daging saja sesuai selera Anda.",
        menu_4_title: "Gule Kikil Kambing", menu_4_short: "Tekstur kikil yang kenyal dan lembut berpadu sempurna dengan kuah gule rempah rahasia khas H. Faqih.", menu_4_char: "Kaya kolagen, lumer di mulut tanpa bau menyengat.", menu_4_desc: "Sajian istimewa bagi penggemar tekstur kenyal. Kikil kambing diolah dengan teknik khusus hingga benar-benar empuk dan tidak bau, lalu dimasak perlahan dalam kuah gule kental kami yang kaya akan rempah-rempah. Sangat nikmat disajikan panas-panas.", menu_4_extra: "Stok terbatas setiap harinya. Tanyakan ketersediaan melalui WhatsApp.",
        
        menu_full_title: "Lihat Menu Selengkapnya",
        menu_full_desc: "Kami menyediakan berbagai hidangan khas Warung Sate H. Faqih 1, mulai dari sate, gule, aneka minuman segar, hingga pilihan pelengkap lainnya. Temukan menu lengkap kami dan langsung pesan melalui platform pengiriman favorit Anda:",

        history_title: "Sejarah & Kisah Pendiri",
        founder_label: "Alm. H. Faqih",
        history_quote: '"Dari ketulusan, perjuangan, dan kesederhanaan, lahirlah warisan rasa yang terus dikenang lintas generasi."',
        history_founder_desc1: "Alm. H. Faqih merupakan salah satu santri yang pernah menimba ilmu di Pondok Pesantren Tebuireng dan termasuk salah satu murid Hadratus Syekh KH. Hasyim Asy’ari. Setelah menimba ilmu, beliau memiliki tekad besar untuk merintis usaha sendiri di tengah kondisi ekonomi yang sulit pada era kemerdekaan. Dengan ketekunan, kesabaran, dan semangat untuk bangkit dari keterpurukan, beliau memulai usaha sate secara sederhana dari sebuah warung kecil berbahan anyaman bambu yang berada di halaman rumah milik pasangan warga keturunan Tionghoa yang kemudian berpindah ke Surabaya. Seiring waktu, usaha tersebut perlahan berkembang menjadi bangunan kayu yang menjadi cikal bakal Warung Sate H. Faqih.",
        history_founder_desc2: "Setelah mengalami perkembangan dan renovasi, bangunan sederhana itu kemudian berubah menjadi rumah makan yang lebih layak untuk melayani pelanggan. Dari tangan beliau, racikan sate dengan cita rasa khas keluarga mulai dikenal oleh masyarakat Cukir, Jombang, hingga tumbuh menjadi salah satu kuliner legendaris sejak sekitar tahun 1950-an. Dalam perkembangannya, usaha yang semula dikenal sebagai Warung Sate H. Faqih ini kemudian diteruskan oleh keluarga dan dikenal hingga sekarang dengan nama Warung Sate H. Faqih 1. Hingga hari ini, semangat, resep, dan cita rasa yang diwariskan Alm. H. Faqih tetap dijaga oleh keluarga penerus, sehingga Warung Sate H. Faqih 1 bukan hanya menjadi tempat makan, tetapi juga ruang nostalgia yang menyimpan kenangan lintas generasi, baik bagi kalangan santri maupun masyarakat luas.",
        timeline_1_period: "1950",
        timeline_1_title: "Awal dari Warung Anyaman Bambu",
        timeline_1_desc: "Berawal dari sebuah warung kecil berbahan anyaman bambu di halaman rumah, Alm. H. Faqih mulai merintis usaha sate dengan ketekunan dan cita rasa khas keluarga.",
        timeline_2_period: "1967-an",
        timeline_2_title: "Berkembang Menjadi Bangunan Kayu",
        timeline_2_desc: "Seiring bertambahnya pelanggan, warung sederhana tersebut perlahan berkembang menjadi bangunan kayu yang menjadi tempat singgah masyarakat, santri, dan pendatang.",
        timeline_3_period: "1978",
        timeline_3_title: "Renovasi Menjadi Rumah Makan",
        timeline_3_desc: "Setelah mengalami perkembangan, bangunan kayu kemudian direnovasi menjadi rumah makan yang lebih layak dan nyaman untuk melayani pelanggan.",
        timeline_4_period: "Masa Kini",
        timeline_4_title: "Diteruskan Lintas Generasi",
        timeline_4_desc: "Warung Sate H. Faqih 1 terus dijaga oleh keluarga penerus dengan mempertahankan resep, cita rasa, dan nilai perjuangan yang diwariskan Alm. H. Faqih.",

        guest_subtitle: "Galeri Foto", guest_title: "Pernah Singgah di Warung Kami", guest_instruction: "Momen hangat para tokoh dan pelanggan yang pernah singgah di warung kami.",
        guest_label_figures: "Foto Tokoh",
        guest_1_name: "KH. Mustofa Bisri, Istri & Ning Alissa Wahid",guest_1_role: "Ulama, Budayawan & Tokoh GUSDURian",guest_1_caption: '"Momen silaturahmi hangat di Warung Sate H. Faqih 1."',guest_1_desc: "Silaturahmi sederhana yang menjadi bagian dari kenangan Warung Sate H. Faqih 1.",
        guest_2_name: "KH. Hasyim Muzadi",guest_2_role: "Ulama & Tokoh Nasional",guest_2_caption: '"Momen hangat saat bersantap di Warung Sate H. Faqih 1."',guest_2_desc: "Kenangan kunjungan KH. Hasyim Muzadi di Warung Sate H. Faqih 1.",
        guest_3_name: "KH. Ishaq Latief & KH. Ridho Amir beserta Istri",guest_3_role: "Ulama & Tokoh Agama",guest_3_caption: '"Momen silaturahmi penuh kehangatan di Warung Sate H. Faqih 1."',guest_3_desc: "Kenangan silaturahmi para tokoh agama yang menjadi bagian dari perjalanan Warung Sate H. Faqih 1.",
        guest_4_name: "Gus Miftah",guest_4_role: "Pendakwah & Pengasuh Ponpes Ora Aji",guest_4_caption: '"Momen silaturahmi hangat di Warung Sate H. Faqih 1."',guest_4_desc: "Kehadiran Gus Miftah menjadi salah satu kenangan berharga dalam perjalanan Warung Sate H. Faqih 1.",
        guest_5_name: "Buya Husein Muhammad & Sahabat Gus Dur",guest_5_role: "Ulama, Cendekiawan & Aktivis HAM",guest_5_caption: '"Momen silaturahmi hangat di Warung Sate H. Faqih 1."',guest_5_desc: "Kehadiran Buya Husein Muhammad menjadi bagian dari kenangan berharga Warung Sate H. Faqih 1.",
        guest_6_name: "Anies Baswedan",guest_6_role: "Akademisi, Aktivis & Tokoh Nasional",guest_6_caption: '"Momen hangat saat bersantap di Warung Sate H. Faqih 1."',guest_6_desc: "Kehadiran Anies Baswedan menjadi bagian dari kenangan berharga Warung Sate H. Faqih 1.",
        guest_7_name: "Khofifah Indar Parawansa beserta Putra",guest_7_role: "Gubernur Jawa Timur & Tokoh Muslimat NU",guest_7_caption: '"Momen silaturahmi hangat di Warung Sate H. Faqih 1."',guest_7_desc: "Kehadiran Khofifah Indar Parawansa menjadi bagian dari kenangan berharga Warung Sate H. Faqih 1.",
        guest_8_name: "Dahlan Iskan beserta Istri",guest_8_role: "Tokoh Pers, Pengusaha Media & Mantan Menteri BUMN",guest_8_caption: '"Momen silaturahmi hangat di Warung Sate H. Faqih 1."',guest_8_desc: "Kehadiran Dahlan Iskan menjadi bagian dari kenangan berharga Warung Sate H. Faqih 1.",
        guest_9_name: "Muhaimin Iskandar / Cak Imin",guest_9_role: "Politisi & Tokoh Nasional",guest_9_caption: '"Silaturahmi penuh kehangatan di Warung Sate H. Faqih 1."',guest_9_desc: "Momen kebersamaan ini menjadi salah satu cerita berharga dalam perjalanan Warung Sate H. Faqih 1.",
        guest_10_name: "Mahfud MD",guest_10_role: "Pakar Hukum Tata Negara & Tokoh Nasional",guest_10_caption: '"Momen silaturahmi hangat di Warung Sate H. Faqih 1."',guest_10_desc: "Kehadiran Mahfud MD menjadi bagian dari kenangan berharga Warung Sate H. Faqih 1.",
        guest_11_name: "Jenderal Pol. Timur Pradopo beserta Rombongan",guest_11_role: "Mantan Kapolri & Tokoh Kepolisian Nasional",guest_11_caption: '"Momen kebersamaan saat bersantap di Warung Sate H. Faqih 1."',guest_11_desc: "Kehadiran Jenderal Pol. Timur Pradopo beserta rombongan menjadi bagian dari kenangan berharga Warung Sate H. Faqih 1.",
        
        visitor_label: "Foto Pengunjung", visitor_intro: "Momen kebersamaan pelanggan yang menjadi bagian dari cerita Warung Sate H. Faqih 1.",
        visitor_1_name: "Makan Bersama di Warung",visitor_1_role: "Suasana Kebersamaan",visitor_1_caption: '"Momen sederhana saat pelanggan berkumpul dan menikmati hidangan di Warung Sate H. Faqih 1."',visitor_1_desc: "Suasana pelanggan saat menikmati hidangan bersama di meja makan, menjadi bagian dari cerita hangat Warung Sate H. Faqih 1.",
        visitor_2_name: "Rombongan Pelanggan",visitor_2_role: "Singgah Bersama",visitor_2_caption: '"Kebersamaan rombongan pelanggan menjadi bagian dari kenangan di Warung Sate H. Faqih 1."',visitor_2_desc: "Kunjungan rombongan pelanggan yang turut menghidupkan suasana warung dan menambah cerita dalam perjalanan Warung Sate H. Faqih 1.",
        visitor_3_name: "Kebersamaan Keluarga",visitor_3_role: "Hangat & Akrab",visitor_3_caption: '"Warung sederhana yang menjadi tempat berkumpul dan menikmati waktu bersama keluarga."',visitor_3_desc: "Momen keluarga yang singgah dan menikmati hidangan khas Warung Sate H. Faqih 1 dalam suasana hangat dan akrab.",
        visitor_4_name: "Pelanggan Setia",visitor_4_role: "Rasa yang Dirindukan",visitor_4_caption: '"Banyak pelanggan kembali bukan hanya karena rasa, tetapi juga karena suasana yang terasa akrab."',visitor_4_desc: "Momen pelanggan setia saat menikmati hidangan di warung, menggambarkan rasa dan suasana yang terus dikenang dari waktu ke waktu.",
        visitor_5_name: "Makan Bersama Keluarga",visitor_5_role: "Cerita Pelanggan",visitor_5_caption: '"Sepiring sate dan gule menjadi pelengkap obrolan hangat bersama keluarga."',visitor_5_desc: "Suasana makan bersama keluarga dengan hidangan sate, gule, dan menu khas yang menjadi favorit pelanggan Warung Sate H. Faqih 1.",
        visitor_6_name: "Singgah dan Bernostalgia",visitor_6_role: "Momen Pelanggan",visitor_6_caption: '"Setiap kunjungan menyimpan cerita, dari rasa yang dikenang hingga suasana yang terasa dekat."',visitor_6_desc: "Momen pelanggan yang singgah dan menikmati hidangan di Warung Sate H. Faqih 1, menjadi bagian dari kenangan sederhana yang berkesan.",

        review_title: "Kata Mereka Tentang Kami", review_subtitle: "Berdasarkan lebih dari 700+ ulasan otentik pelanggan di Google Maps.", review_btn: "Lihat Semua Ulasan di Google Maps",
        rev_1: '"Makanannya enak dan sedaap, apabila ingin menyantap satai ayam/kambing dan makanan lainnya enak mampir di sate Faqih nih. Yang punya darah rendah jg joz langsung berkeringat setelah mam menambah energi. Barokallah semuanya"',
        rev_2: '"Wajib mampir ke sini kalo sambang anak di Jombang. Satenya empuk dan bumbu kacangnya pun nikmat..."',
        rev_3: '"Langganan sate kl ke Jombang, harga tidak murah tp juga tidak mahal. Rasa sate lumayan enak. Gulenya tidak berbau"',
        rev_4: '"Sate dan gulenya mantap! Potongan daging besar-besar, kuah gule medok rempahnya berasa banget. Wajib mampir kalau lagi di Jombang atau lewat Mojowarno."',
        rev_5: '"Warung sate legendaris<br>Sangat lezat sampai sekarang<br>Empuk dan bumbu rasa kacang sangat nendang<br>Maknyus sekali"',
        rev_6: '"Alhamdulillah, sudah tahun-tahunan makan Sate di Warung Sate H. Faqih. Sejak dari umur 15 tahun. Satenya enak, banyak gajih dan pesan untuk yang hati saja juga bisa. Cocok untuk keluarga besar untuk makan di sini. Semoga nanti pulang dari perantauan terus balik ke Jombang bisa makan di sini lagi."',
        rev_7: '"rasa gule nya endul banget guysss trus sate nya juga enak lah ya tapi gule nya yang paling suedeppp pollll."',
        rev_8: '"Dulu langganan alm. Ayah saya. Sekarang lebih sepi daripada yg dulu. Tapi tetap menjaga rasa, kebersihan dan keramahan."',
        review_time_1: "seminggu yang lalu", review_time_2: "2 bulan lalu", review_time_3: "5 bulan lalu", review_time_4: "5 bulan lalu", review_time_5: "8 bulan lalu", review_time_6: "1 tahun lalu", review_time_7: "1 tahun lalu", review_time_8: "1 tahun lalu",
        
        faq_subtitle: "Informasi Pelanggan", faq_title: "Pertanyaan Seputar Warung",
        faq_q1: "Apakah melayani pesanan aqiqah?", faq_a1: "Tentu saja. Kami melayani acara aqiqah. Kami sarankan untuk menghubungi nomor WhatsApp kami minimal H-3 agar kami dapat mempersiapkan kualitas daging dan layanan terbaik.",
        faq_q2: "Apakah bisa melakukan reservasi tempat untuk akhir pekan?", faq_a2: "Ya, sangat bisa. Menjelang akhir pekan atau hari libur nasional, warung kami biasanya sangat ramai. Agar tidak perlu antri meja, Anda bisa melakukan reservasi tempat melalui WhatsApp dengan menyebutkan jumlah rombongan dan estimasi jam kedatangan.",
        faq_q3: "Bagaimana cara agar sate tetap enak jika dibawa pulang ke luar kota?", faq_a3: "Jika Anda ingin membawa sate sebagai oleh-oleh ke luar kota (perjalanan lebih dari 3 jam), sampaikan kepada kasir/pelayan kami. Kami akan mengemas bumbu kacang/kecap secara terpisah dan memastikan sate dibakar dengan tingkat kematangan yang aman untuk dipanaskan ulang (di-microwave/teflon) di rumah.",

        loc_btn_map: "Buka Rute di Google Maps",

        loc_title: "Kunjungi & Pesan", loc_desc: "Nikmati sajian legendaris langsung di tempat kami dengan kehangatan khas H. Faqih 1, atau pesan melalui platform online untuk dinikmati bersama keluarga di rumah.",
        loc_hours: "Jam Operasional", loc_hours_value: "Setiap Hari: 08:00 - 20:00 WIB", order_title: "Pesan Online", order_subtitle: "Pilih platform pengiriman favorit Anda untuk memesan, atau hubungi kami langsung melalui WhatsApp.", btn_wa_large: "Pesan & Tanya Menu via WhatsApp",
        modal_cta: "Tanya / Pesan Menu Ini", btn_pesan_wa: "Pesan via WA", btn_order_apps: "Order di App",
        
        footer_desc: "Warung Sate H. Faqih 1 menyajikan kelezatan sate legendaris dengan resep warisan keluarga yang dijaga sejak 1950.", footer_badge_since: "Sejak 1950", footer_badge_recipe: "Resep Warisan", footer_contact: "Hubungi Kami", footer_social: "Media Sosial",
        footer_social_desc: "Ikuti kami untuk melihat kabar terbaru, menu pilihan, dan suasana Warung Sate H. Faqih 1.", footer_tagline_1: "Warisan rasa sejak 1950.", footer_tagline_2: "Kelezatan yang dikenang lintas generasi.",
        footer_feedback: "Kritik & Saran", footer_feedback_wa_text: "Halo Warung Sate H. Faqih 1, saya ingin menyampaikan saran...", footer_copyright: "Hak Cipta &copy; <span id='year'>2024</span> Warung Sate H. Faqih 1. Semua Hak Dilindungi.", wa_floating_tooltip: "Chat WhatsApp"
    },
    en: {
        top_promo: "🔥 Open Daily 08:00 - 20:00 | Dine-in, Takeaway & Online Delivery",
        nav_order: "Order", hero_btn_order: "Order Now", hero_btn_menu: "View Menu",
        gallery_text: "@sate.faqih1",

        nav_about: "About", nav_menu: "Menu", nav_history: "History", nav_guests: "Photo Gallery", nav_reviews: "Reviews", nav_faq: "FAQ", nav_location: "Location",
        
        hero_badge_0: "Cross-Generation Heritage", hero_title_0_main: "Warung Sate", hero_title_0_sub: "H. Faqih 1", hero_sub_0: "Legendary since 1950. More than just delicious satay, it has silently witnessed togetherness, nostalgia, and your family stories.",
        hero_sub_0_mobile: "Legendary since 1950. A place of flavor, togetherness, and memories across generations.",
        hero_sub_0_tablet: "Legendary since 1950. A humble place filled with flavor, togetherness, and memories across generations.",
        hero_badge_1: "Authentic Taste", hero_title_1_main: "Mutton Satay", hero_title_1_sub: "Legendary", hero_sub_1: "Goat satay, grilled to perfection, is served with a savory peanut or soy sauce glaze, topped with fresh red onions, and accompanied by spicy sambal. The combination of tender meat, the aroma of charcoal grilling, and signature seasonings delivers an authentic satay flavor.",
        hero_sub_1_mobile: "Tender goat satay with savory sauce, smoky aroma, shallots, and spicy sambal.",
        hero_sub_1_tablet: "Tender goat satay with savory sauce, smoky charcoal aroma, fresh shallots, and spicy sambal.",
        hero_badge_2: "Rich & Flavorful Broth", hero_title_2_main: "Mutton Curry", hero_title_2_sub: "Special", hero_sub_2: "Slow-cooked for hours resulting in super tender meat with a thick, heartwarming Indonesian spice broth.",
        hero_sub_2_mobile: "Tender goat curry with warm, rich Indonesian spiced broth.",
        hero_sub_2_tablet: "Slow-cooked until tender, with warm, rich, and flavorful Indonesian spiced broth.",
        
        nostalgia_title: "A Room of Cross-Generational Memories",
        nostalgia_desc: "Warung Sate H. Faqih 1 is more than just a place to stop and dine. Here, our tables and chairs have silently witnessed grandparents introducing authentic flavors to their grandchildren, as well as <span class='font-bold text-brand-orange'>students, local residents, families, and visitors</span> who keep coming back for the distinctive taste of Cukir. Every wisp of satay smoke carries warmth, stories, togetherness, and bonds that have never faded since 1950.",
        
        fac_title: "Your Comfort is Our Priority", fac_1: "Comfortable Atmosphere", fac_2: "Family Friendly", fac_3: "Great for Groups", fac_4: "Friendly Service",

        menu_subtitle: "A Heritage of Flavor", menu_title: "Our Signature Menu", menu_instruction: "Click photo to view menu details.",
        menu_badge_best: "Best Seller", menu_badge_family: "Family Favorite", menu_badge_recommended: "Recommended", menu_badge_texture: "Texture Lover Favorite", menu_detail_link: "Click for Details",
        menu_type_sate: "Satay Varieties", menu_type_gule: "Curry & Soup Variants",
        menu_1_title: "Mutton Satay", menu_1_short: "Premium cuts of highly tender mutton, perfectly grilled over charcoal.", menu_1_char: "No odor, served with sweet soy sauce & fresh shallots.", menu_1_desc: "This is our timeless signature dish. Using selected mutton cut to the perfect size, then grilled over wood charcoal to achieve the perfect level of doneness. The meat is tender, juicy, and entirely free of any strong odor.", menu_1_extra: "Highly recommended to be enjoyed with warm rice and hot sweet tea.",
        menu_2_title: "Legendary Chicken Satay", menu_2_short: "Thick and juicy chicken meat, generously coated in our secret, rich peanut sauce.", menu_2_char: "Manually ground peanut sauce, authentic texture.", menu_2_desc: "A favorite across generations. Fresh chicken meat grilled until browned, poured with H. Faqih's heritage recipe peanut sauce which is manually processed to maintain its thick texture and distinctive savory-sweet taste.", menu_2_extra: "Children's favorite menu and suitable for large family dining portions.",
        menu_3_title: "Special Mutton Curry (Gule)", menu_3_short: "Thick coconut milk curry rich in Indonesian spices, slow-cooked with meat and bones.", menu_3_char: "Rich broth, meat easily falls off the bone.", menu_3_desc: "The mandatory companion to eating satay. Our gule broth is cooked for hours using selected traditional spices, resulting in a thick, rich, and highly flavorful broth. The meat and offal inside are incredibly tender.", menu_3_extra: "Can be ordered with mixed fillings or just meat according to your preference.",
        menu_4_title: "Mutton Tendon Curry", menu_4_short: "Chewy and tender mutton tendon blended perfectly with our secret spice curry broth.", menu_4_char: "Rich in collagen, melts in the mouth without strong odor.", menu_4_desc: "A special dish for lovers of chewy textures. Mutton tendon is processed with a special technique until it is completely tender and odorless, then slow-cooked in our thick, spice-rich curry broth. Best enjoyed hot.", menu_4_extra: "Limited stock available daily. Ask for availability via WhatsApp.",
        
        menu_full_title: "View Our Full Menu",
        menu_full_desc: "We offer a variety of signature dishes from Warung Sate H. Faqih 1, ranging from satay and gulai to a selection of refreshing drinks and other side dishes. Check out our full menu and order directly through your favorite delivery platform:",

        history_title: "History & Founder's Story",
        founder_label: "The Late H. Faqih",
        history_quote: '"From sincerity, struggle, and simplicity came a legacy of flavor remembered across generations."',
        history_founder_desc1: "The late H. Faqih was once a student at Tebuireng Islamic Boarding School and was among the students of Hadratus Syekh KH. Hasyim Asyari. After completing his studies, he carried a strong determination to build his own livelihood amid the difficult economic conditions of the post-independence era. With perseverance, patience, and the spirit to rise from hardship, he began his satay business humbly from a small bamboo-woven stall in the yard of a Chinese-Indonesian family's home, whose owners later moved to Surabaya. Over time, the business gradually grew into a wooden building that became the forerunner of Warung Sate H. Faqih.",
        history_founder_desc2: "After years of growth and renovation, the simple building was transformed into a more proper restaurant to serve customers better. From his hands, satay made with a distinctive family flavor became known among the people of Cukir, Jombang, and eventually grew into one of the area's legendary culinary destinations since around the 1950s. In its development, the business that was first known as Warung Sate H. Faqih was later continued by the family and is now known as Warung Sate H. Faqih 1. To this day, the spirit, recipes, and flavors inherited from the late H. Faqih are preserved by the next generation, making Warung Sate H. Faqih 1 not only a place to eat, but also a space of nostalgia that holds cross-generational memories for both boarding school communities and the wider public.",
        timeline_1_period: "1950",
        timeline_1_title: "The Beginning of a Bamboo-Woven Stall",
        timeline_1_desc: "Starting from a small bamboo-woven stall in the family yard, the late H. Faqih began building his satay business with perseverance and a distinctive family flavor.",
        timeline_2_period: "Around 1967",
        timeline_2_title: "Growing into a Wooden Building",
        timeline_2_desc: "As more customers came, the simple stall gradually grew into a wooden building that became a stopover for local residents, students, and visitors.",
        timeline_3_period: "1978",
        timeline_3_title: "Renovated into a Restaurant",
        timeline_3_desc: "After years of growth, the wooden building was renovated into a more proper and comfortable restaurant to serve customers better.",
        timeline_4_period: "Today",
        timeline_4_title: "Continued Across Generations",
        timeline_4_desc: "Warung Sate H. Faqih 1 continues to be cared for by the next generation of the family while preserving the recipes, flavors, and values inherited from the late H. Faqih.",

        guest_subtitle: "Photo Gallery", guest_title: "They Have Visited Our Restaurant", guest_instruction: "Warm moments of notable figures and customers who have visited our restaurant.",
        guest_label_figures: "Notable Guests",
        guest_1_name: "KH. Mustofa Bisri, His Wife & Ning Alissa Wahid", guest_1_role: "Islamic Scholar, Cultural Figure & GUSDURian Figure", guest_1_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_1_desc: "A simple gathering that became part of the cherished memories of Warung Sate H. Faqih 1.",
        guest_2_name: "KH. Hasyim Muzadi", guest_2_role: "Islamic Scholar & National Figure", guest_2_caption: '"A warm dining moment at Warung Sate H. Faqih 1."', guest_2_desc: "A memorable visit by KH. Hasyim Muzadi to Warung Sate H. Faqih 1.",
        guest_3_name: "KH. Ishaq Latief & KH. Ridho Amir with Their Wives", guest_3_role: "Islamic Scholars & Religious Figures", guest_3_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_3_desc: "A memorable gathering of religious figures that became part of the journey of Warung Sate H. Faqih 1.",
        guest_4_name: "Gus Miftah", guest_4_role: "Preacher & Caretaker of Ora Aji Islamic Boarding School", guest_4_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_4_desc: "The visit of Gus Miftah became part of the cherished memories of Warung Sate H. Faqih 1.",
        guest_5_name: "Buya Husein Muhammad & Friends of Gus Dur", guest_5_role: "Islamic Scholar, Intellectual & Human Rights Activist", guest_5_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_5_desc: "The visit of Buya Husein Muhammad became part of the cherished memories of Warung Sate H. Faqih 1.",
        guest_6_name: "Anies Baswedan", guest_6_role: "Academic, Activist & National Figure", guest_6_caption: '"A warm dining moment at Warung Sate H. Faqih 1."', guest_6_desc: "The visit of Anies Baswedan became part of the cherished memories of Warung Sate H. Faqih 1.",
        guest_7_name: "Khofifah Indar Parawansa with Her Son", guest_7_role: "Governor of East Java & Muslimat NU Figure", guest_7_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_7_desc: "The visit of Khofifah Indar Parawansa became part of the cherished memories of Warung Sate H. Faqih 1.",
        guest_8_name: "Dahlan Iskan with His Wife", guest_8_role: "Press Figure, Media Entrepreneur & Former Minister of State-Owned Enterprises", guest_8_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_8_desc: "The visit of Dahlan Iskan became part of the cherished memories of Warung Sate H. Faqih 1.",
        guest_9_name: "Muhaimin Iskandar / Cak Imin", guest_9_role: "Politician & National Figure", guest_9_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_9_desc: "This moment of togetherness became one of the cherished stories in the journey of Warung Sate H. Faqih 1.",
        guest_10_name: "Mahfud MD", guest_10_role: "Constitutional Law Expert & National Figure", guest_10_caption: '"A warm moment of togetherness at Warung Sate H. Faqih 1."', guest_10_desc: "The visit of Mahfud MD became part of the cherished memories of Warung Sate H. Faqih 1.",
        guest_11_name: "General Pol. Timur Pradopo with His Entourage", guest_11_role: "Former Indonesian National Police Chief & National Police Figure", guest_11_caption: '"A warm dining moment at Warung Sate H. Faqih 1."', guest_11_desc: "The visit of General Pol. Timur Pradopo and his entourage became part of the cherished memories of Warung Sate H. Faqih 1.",

        visitor_label: "Visitor Photos", visitor_intro: "Togetherness from customers enjoying satay, gule, and our signature dishes.",
        visitor_1_name: "Family Meal", visitor_1_role: "Togetherness Moment", visitor_1_caption: '"A simple place that is always a favorite choice for gathering with family."', visitor_1_desc: "A family moment enjoying our signature dishes at Warung Sate H. Faqih 1.",
        visitor_2_name: "Lunch Atmosphere", visitor_2_role: "Lively & Warm", visitor_2_caption: '"The aroma of grilled satay and the lively atmosphere become part of customers memories."', visitor_2_desc: "A warm lunch atmosphere with the aroma of grilled satay and freshly served gule.",
        visitor_3_name: "Restaurant Atmosphere", visitor_3_role: "Favorite Stopover", visitor_3_caption: '"Many customers come not only to eat, but also to relive memories."', visitor_3_desc: "A simple restaurant that has become a favorite stop for customers across generations.",
        visitor_4_name: "Loyal Customers", visitor_4_role: "Stories Across Generations", visitor_4_caption: '"From generation to generation, the taste and atmosphere still hold a place in our hearts."', visitor_4_desc: "Stories of loyal customers who keep returning for the flavors and atmosphere preserved over time.",
        visitor_5_name: "Lunch Together", visitor_5_role: "Warm & Familiar", visitor_5_caption: '"A plate of warm satay always makes family conversations feel closer."', visitor_5_desc: "A warm customer lunch atmosphere with our signature satay and gule.",
        visitor_6_name: "Stopping By Together", visitor_6_role: "Customer Stories", visitor_6_caption: '"Every visit keeps a new story in a restaurant that always feels familiar."', visitor_6_desc: "A customer moment enjoying the atmosphere of Warung Sate H. Faqih 1.",

        review_title: "What They Say About Us", review_subtitle: "Based on over 700+ authentic customer reviews on Google Maps.", review_btn: "View All Reviews on Google Maps",
        rev_1: '"The food is delicious. If you want to enjoy chicken or mutton satay and other tasty dishes, stop by Sate Faqih. Everything is excellent."',
        rev_2: '"A must-visit when visiting family in Jombang. The satay is tender and the peanut sauce is delicious..."',
        rev_3: '"My regular satay stop when I go to Jombang. The price is fair, the satay tastes good, and the gule has no strong smell."',
        rev_4: '"The satay and gule are amazing! Big meat cuts, rich spice broth. A must-visit when in Jombang or passing through Mojowarno."',
        rev_5: '"Legendary satay stall<br>Still very delicious today<br>Tender meat and bold peanut sauce<br>Absolutely satisfying"',
        rev_6: '"Alhamdulillah, I have been eating satay at Warung Sate H. Faqih for years, since I was 15. The satay is delicious and great for large family meals. I hope I can eat here again whenever I return to Jombang."',
        rev_7: '"The gule tastes really great, and the satay is good too, but the gule is the standout."',
        rev_8: '"This used to be my late father regular place. It is quieter now than before, but it still maintains its taste, cleanliness, and hospitality."',
        review_time_1: "a week ago", review_time_2: "2 months ago", review_time_3: "5 months ago", review_time_4: "5 months ago", review_time_5: "8 months ago", review_time_6: "1 year ago", review_time_7: "1 year ago", review_time_8: "1 year ago",

        faq_subtitle: "Customer Information", faq_title: "Frequently Asked Questions",
        faq_q1: "Do you serve aqiqah orders?", faq_a1: "Of course. We serve aqiqah events. We recommend contacting us via WhatsApp at least three days in advance so we can prepare the best meat quality and service.",
        faq_q2: "Can I reserve a table for the weekend?", faq_a2: "Yes, absolutely. On weekends or national holidays, our restaurant is usually very busy. To avoid waiting for a table, you can make a reservation via WhatsApp by mentioning your group size and estimated arrival time.",
        faq_q3: "How can I keep the satay delicious when taking it out of town?", faq_a3: "If you would like to take satay out of town as a gift, especially for trips longer than three hours, please inform our cashier or staff. We will pack the peanut sauce or sweet soy sauce separately and make sure the satay is grilled to a level that is safe for reheating at home.",

        loc_btn_map: "Open Route in Google Maps",

        loc_title: "Visit & Order", loc_desc: "Enjoy legendary dishes directly at our place with the signature warmth of H. Faqih 1, or order through online platforms to enjoy with family at home.",
        loc_hours: "Operating Hours", loc_hours_value: "Daily: 08:00 - 20:00 WIB", order_title: "Order Online", order_subtitle: "Choose your favorite delivery platform to order, or contact us directly via WhatsApp.", btn_wa_large: "Order & Inquire via WhatsApp",
        modal_cta: "Ask / Order This Menu", btn_pesan_wa: "Order via WA", btn_order_apps: "Order on App",
        
        footer_desc: "Warung Sate H. Faqih 1 serves legendary satay delicacies with a family heritage recipe guarded since 1950.", footer_badge_since: "Since 1950", footer_badge_recipe: "Heritage Recipe", footer_contact: "Contact Us", footer_social: "Social Media",
        footer_social_desc: "Follow us for the latest updates, featured menus, and the atmosphere of Warung Sate H. Faqih 1.", footer_tagline_1: "Heritage flavors since 1950.", footer_tagline_2: "A taste remembered across generations.",
        footer_feedback: "Feedback & Suggestions", footer_feedback_wa_text: "Hello Warung Sate H. Faqih 1, I would like to share feedback...", footer_copyright: "Copyright &copy; <span id='year'>2024</span> Warung Sate H. Faqih 1. All Rights Reserved.", wa_floating_tooltip: "Chat on WhatsApp"
    }
};
